.\" Manpage for pgg.
.\" Contact nicolo.santamaria@gmail.com for bug reports.
.TH pgg 1 "07-10-2019" "pgg man page"

.SH NAME
pgg \- Post from the Get-Go

.SH SYNOPSIS
.B pgg [-m GET] [-e foo] [-c config-file] http://example.com/{{my_var}}

.SH DESCRIPTION
Pgg \- Post from the Get-Go.
.PP
Pgg is a client you can use to send http requests while taking advantage of custom environments set in a configuration file.

.SH OPTIONS
.B "-m, -method"
    Specify the request method.

.B "-e, -env"
    Specify the environment to use.

.B "-c, -cfg"
    Specify an alternative config file.


.B "-h"
    Prints the help message.

.B "--help"
    Prints options details.

.SH FILES
.B ~/.config/pgg/config
    When starting pgg looks for configuration files in the following order:

      1. ~/.config/pgg/config

      2. ~/.pgg/config

    You can specify a custom path using the -c option.
    The config file must be written in TOML style.
    The variables defined in the environments can be accessed by enclosing their name in double curly brackets.

    For example running:
      pgg -e foo 'http://example.com/{{foo}}/{{name}}'

    will result in a GET request to
      http://example.com/bar/pgg.


.B    Sample configuration
.PP
    # pgg config file

    # Set the default environment.
    default_env = "foo"
    [env]
        # Add a custom environment named "foo".
        [env.foo]
        scheme = "http://"
        vars = [
            "foo=bar",
            "name=pgg"
        ]

        # Add a custom environment named "bar".
        [env.bar]
        scheme = "ftp://"
        vars = [
            "base_url=www.example.com"
        ]


.SH ENVIRONMENT
.B HOME
    This variable is used to read the config file
.I $HOME/.config/pgg/config

.SH AUTHOR
Nicolò Santamaria <nicolo.santamaria@gmail.com>
